[package]
name = "tauri-plugin-mobile-import"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-mobile-import"
build = "build.rs"

[lib]
name = "tauri_plugin_mobile_import"
path = "src/lib.rs"

[dependencies]
tauri = { version = "2", default-features = false }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
